name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy-sdist:

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/pytorchltr2
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        python setup.py build_ext
    - name: Build source wheel
      run: |
        python setup.py sdist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
